require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

# ---------------------- Layout -----------------------

Layout/LineLength:
  Max: 120

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - loqate.gemspec

Naming/MethodName:
  Exclude:
    - lib/loqate/result.rb

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
