require: rubocop-rspec

AllCops:
  DisplayCopNames: true

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - loqate.gemspec

Metrics/LineLength:
  Max: 120

Naming/MethodName:
  Exclude:
    - lib/loqate/result.rb

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
