threshold: 100
rules:
  ApiTag::Presence:
    enabled: false
    exclude: []
  ApiTag::Inclusion:
    enabled: false
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Loqate::Address#==
      - Loqate::Address#attributes
      - Loqate::Address#id
      - Loqate::Address#initialize
      - Loqate::Address#type
      - Loqate::Address#text
      - Loqate::Address#highlight
      - Loqate::Address#description
      - Loqate::AddressGateway#initialize
      - Loqate::APIResult#errors?
      - Loqate::APIResult#items
      - Loqate::APIResult#initialize
      - Loqate::BatchEmailValidation#status
      - Loqate::BatchEmailValidation#email_address
      - Loqate::BatchEmailValidation#account
      - Loqate::BatchEmailValidation#domain
      - Loqate::BatchEmailValidation#is_disposible
      - Loqate::BatchEmailValidation#is_system_mailbox
      - Loqate::Configuration#api_key
      - Loqate::Configuration#host
      - Loqate::Configuration#language
      - Loqate::Configuration#initialize
      - Loqate::DetailedAddress#initialize
      - Loqate::DetailedAddress#==
      - Loqate::EmailGateway#initialize
      - Loqate::EmailValidation#response_code
      - Loqate::EmailValidation#response_message
      - Loqate::EmailValidation#email_address
      - Loqate::EmailValidation#user_account
      - Loqate::EmailValidation#domain
      - Loqate::EmailValidation#is_disposable_or_temporary
      - Loqate::EmailValidation#is_complainer_or_fraud_risk
      - Loqate::EmailValidation#duration
      - Loqate::EmailValidation#valid?
      - Loqate::EmailValidation#valid_domain?
      - Loqate::EmailValidation#invalid?
      - Loqate::EmailValidation#timeout?
      - Loqate::Error#id
      - Loqate::Error#description
      - Loqate::Error#cause
      - Loqate::Error#resolution
      - Loqate::Error#initialize
      - Loqate::Gateway#config
      - Loqate::Gateway#initialize
      - Loqate::Gateway#address
      - Loqate::Gateway#email
      - Loqate::Gateway#phone
      - Loqate::PhoneGateway#initialize
      - Loqate::PhoneNumberValidation#phone_number
      - Loqate::PhoneNumberValidation#request_processed
      - Loqate::PhoneNumberValidation#is_valid
      - Loqate::PhoneNumberValidation#network_code
      - Loqate::PhoneNumberValidation#network_name
      - Loqate::PhoneNumberValidation#network_country
      - Loqate::PhoneNumberValidation#national_format
      - Loqate::PhoneNumberValidation#country_prefix
      - Loqate::PhoneNumberValidation#number_type
      - Loqate::PhoneNumberValidation#valid?
      - Loqate::Result::Success#success?
      - Loqate::Result::Success#failure?
      - Loqate::Result::Failure#success?
      - Loqate::Result::Failure#failure?
      - Loqate::Result#code
      - Loqate::Result#value
      - Loqate::Result::Failure#error
  ReturnTag:
    enabled: true
    exclude:
      - Loqate::Address#==
      - Loqate::Address#attributes
      - Loqate::Address#id
      - Loqate::Address#type
      - Loqate::Address#text
      - Loqate::Address#highlight
      - Loqate::Address#description
      - Loqate::AddressGateway#client
      - Loqate::AddressGateway#mapper
      - Loqate::AddressGateway#error_mapper
      - Loqate::AddressGateway#build_error_from
      - Loqate::AddressGateway#build_addresses_from
      - Loqate::AddressGateway#build_detailed_address_from
      - Loqate::Client#configuration
      - Loqate::Client#authenticate_params
      - Loqate::Client#format_params
      - Loqate::Client#headers
      - Loqate::DetailedAddress#==
      - Loqate::EmailGateway#error_mapper
      - Loqate::EmailGateway#client
      - Loqate::EmailGateway#mapper
      - Loqate::EmailGateway#build_error_from
      - Loqate::EmailGateway#build_email_validation_from
      - Loqate::EmailGateway#build_email_validations_from
      - Loqate::Util.camelize
      - Loqate::Util#camelize
      - Loqate::Util.underscore
      - Loqate::Util#underscore
      - Loqate::Error#attributes
      - Loqate::Gateway#client
      - Loqate::PhoneGateway#mapper
      - Loqate::PhoneGateway#error_mapper
      - Loqate::PhoneGateway#client
      - Loqate::PhoneGateway#build_error_from
      - Loqate::PhoneGateway#build_phone_validation_from
      - Loqate::Result::Failure#error
  Summary::Presence:
    enabled: true
    exclude:
      - Loqate::Address#==
      - Loqate::Address#attributes
      - Loqate::Address#id
      - Loqate::Address#type
      - Loqate::Address#text
      - Loqate::Address#highlight
      - Loqate::Address#description
      - Loqate::AddressGateway#client
      - Loqate::AddressGateway#mapper
      - Loqate::AddressGateway#error_mapper
      - Loqate::AddressGateway#build_error_from
      - Loqate::AddressGateway#build_addresses_from
      - Loqate::AddressGateway#build_detailed_address_from
      - Loqate::Client#configuration
      - Loqate::Client#authenticate_params
      - Loqate::Client#format_params
      - Loqate::Client#headers
      - Loqate::DetailedAddress#initialize
      - Loqate::DetailedAddress#==
      - Loqate::EmailGateway#error_mapper
      - Loqate::EmailGateway#client
      - Loqate::EmailGateway#mapper
      - Loqate::EmailGateway#build_error_from
      - Loqate::EmailGateway#build_email_validation_from
      - Loqate::EmailGateway#build_email_validations_from
      - Loqate::Error#attributes
      - Loqate::Gateway#client
      - Loqate::PhoneGateway#mapper
      - Loqate::PhoneGateway#error_mapper
      - Loqate::PhoneGateway#client
      - Loqate::PhoneGateway#build_error_from
      - Loqate::PhoneGateway#build_phone_validation_from
      - Loqate::Result::Failure#error
  Summary::Length:
    enabled: false
  Summary::Delimiter:
    enabled: false
    exclude: []
  Summary::SingleLine:
    enabled: false
    exclude: []
